inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.4

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/IfUnlessModifier:
  Enabled: false

Layout/IndentHash:
  EnforcedStyle: consistent

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Layout/MultilineMethodCallBraceLayout:
  Enabled: false

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Style/DoubleNegation:
  Enabled: false

Style/RegexpLiteral:
  AllowInnerSlashes: true

Style/WordArray:
  EnforcedStyle: brackets

Style/DateTime:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded
