inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.4

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/IfUnlessModifier:
  Enabled: false

Layout/IndentHash:
  EnforcedStyle: consistent

Style/Documentation:
  Enabled: false
